In [ ]:
import pandas as pd

In [8]:
dt = {'Id':[11,12,13,14,15],
      'first_name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['Hyd','Hyd','Hyd','Hyd','Hyd']}
mydt = pd.DataFrame(dt)
      
                                                                                                               

In [9]:
print(mydt)

   Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd


In [ ]:
import os

In [30]:
os.chdir("PathFile")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'PathFile'

In [22]:
mydt.to_csv('working File.csv',index=False)

In [23]:
pwd

'C:\\Users\\CSW'

### numpy package

In [31]:
import numpy as np

In [34]:
li = [1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [36]:
array = np.array(li)
print(array)

[1 2 3 4 5]


In [39]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)

(2, 3)


In [42]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [43]:
a1= np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [46]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
